#!/bin/bash

# INFO O CPU

cpu()
{
echo -e "\nModel procesora: $(cat /proc/cpuinfo |grep 'model name')\n"
echo -e "Taktowanie procesora: $(cat /proc/cpuinfo |grep 'cpu MHz')\n"
menu 
}

# INFO O RAM

ram()
{
echo -e "\nCala pamiec RAM $(cat /proc/meminfo | grep 'MemTotal')\n"
echo -e "Wolna pamie RAM $(cat /proc/meminfo | grep 'MemFree')\n"
menuc
}

# INFO O DYSKU I PARTYCJACH

disk()
{
echo -e "\n\n$(cat /proc/partitions)\n\n"
menu
}

# INFO O PARTYCJI SWAP

swap()
{
echo -e "\n\n\n$(cat /proc/swaps)\n\n\n"
menu
}

# INFO O WERSJI JÄ„DRA

jadro()
{
echo -e "\n\n\n$(cat /proc/version)\n\n\n"
menu
}

menu()
{
echo -e "SKRYPT WYSWIETLAJACY INFORMACJE O SYSTEMIE\n"
echo -e "Wybierz opcje:\n"
echo "1. Wyswietl informacje o procesorze."
echo "2. Wyswietl informacje o pamieci RAM."
echo "3. Wyswietl informacje o partycjach."
echo "4. Wyswietl informacje o partycji SWAP."
echo "5. Wyswietl informacje o wersji jadra."
echo -e "\nWcisnij q, aby wyjsc."
echo -ne "\nTwoj wybor: " 
}

menu
while [ 0 ]; do
    read odp
    case $odp in
        "1") cpu ;;
        "2") ram ;;
  "3") disk ;;
	"4") swap ;;
	"5") jadro ;;
        "q") exit 0 ;;
        *) echo "Aby wybrac, wcisnij 1-5 lub wyjdz, wciskajac q."
    esac
done
